// vuejs-vuetify/able-pro-vuetify-vuejs-1.5.0/full-version/src/views/dashboards/default/components/WelcomeBanner.vue
<script setup lang="ts">
// assets
import Banner from '@/assets/images/analytics/welcome-banner.png';
</script>

<template>
  <v-card class="welcomeBanner text-white overflow-hidden" elevation="0" rounded="lg">
    <v-card-text class="py-5 px-md-12 px-6">
      <v-row>
        <v-col cols="12" xl="6" md="7" sm="10">
          <div class="pb-md-8 pt-md-7 pt-5 pb-6">
            <h2 class="text-sm-h2 text-h3">Explore Redesigned Able Pro</h2>
            <p class="text-h6 mb-7">
              The Brand new User Interface with power of Material-UI Components. Explore the Endless possibilities with Able Pro.
            </p>
            <v-btn color="white" variant="outlined" rounded="md">Exclusive on Themeforest</v-btn>
          </div>
        </v-col>
        <v-col cols="12" xl="6" md="5" class="d-md-block d-none">
          <div class="pe-8">
            <v-img :src="Banner" cover class="ms-auto" width="200" alt="welcome banner" />
          </div>
        </v-col>
      </v-row>
    </v-card-text>
  </v-card>
</template>
<style lang="scss">
.welcomeBanner {
  background: rgb(var(--v-theme-darkprimary));
  position: relative;
  &::after {
    content: '';
    background-image: url(@/assets/images/analytics/img-dropbox-bg.svg);
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: -1;
    opacity: 0.5;
    background-position: bottom right;
    background-size: 100%;
    background-repeat: no-repeat;
  }
}
</style>

// nextjs/javascript/full-version/src/sections/dashboard/default/WelcomeBanner.jsx
// material-ui
import Button from '@mui/material/Button';
import CardMedia from '@mui/material/CardMedia';
import Grid from '@mui/material/Grid';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';

// project-imports
import MainCard from 'components/MainCard';

// assets
const cardBack = '/assets/images/widget/img-dropbox-bg.svg';
const WelcomeImage = '/assets/images/analytics/welcome-banner.png';

// ==============================|| ANALYTICS - WELCOME ||============================== //

export default function WelcomeBanner() {
  return (
    <MainCard
      border={false}
      sx={(theme) => ({
        color: 'background.paper',
        bgcolor: 'primary.darker',
        ...theme.applyStyles('dark', { color: 'text.primary', bgcolor: 'primary.400' }),
        '&:after': {
          content: '""',
          background: `url("${cardBack}") 100% 100% / cover no-repeat`,
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          zIndex: 1,
          opacity: 0.5
        }
      })}
    >
      <Grid container>
        <Grid size={{ md: 6, sm: 6, xs: 12 }}>
          <Stack sx={{ gap: 2, padding: 3 }}>
            <Typography variant="h2">Explore Redesigned Able Pro</Typography>
            <Typography variant="h6">
              The Brand new User Interface with power of Material-UI Components. Explore the Endless possibilities with Able Pro.
            </Typography>
            <Box sx={{ pt: 1.5 }}>
              <Button
                variant="outlined"
                color="secondary"
                href="https://1.envato.market/c/1289604/275988/4415?subId1=phoenixcoded&u=https%3A%2F%2Fthemeforest.net%2Fitem%2Fable-pro-responsive-bootstrap-4-admin-template%2F19300403"
                sx={(theme) => ({
                  color: 'background.paper',
                  borderColor: 'background.paper',
                  ...theme.applyStyles('dark', { color: 'text.primary', borderColor: 'text.primary' }),
                  zIndex: 2,
                  '&:hover': {
                    color: 'background.paper',
                    borderColor: 'background.paper',
                    bgcolor: 'primary.main',
                    ...theme.applyStyles('dark', { color: 'text.primary', borderColor: 'text.primary' })
                  }
                })}
                target="_blank"
              >
                Exclusive on Themeforest
              </Button>
            </Box>
          </Stack>
        </Grid>
        <Grid sx={{ display: { xs: 'none', sm: 'initial' } }} size={{ sm: 6, xs: 12 }}>
          <Stack sx={{ justifyContent: 'center', alignItems: 'flex-end', position: 'relative', pr: { sm: 3, md: 8 }, zIndex: 2 }}>
            <CardMedia component="img" sx={{ width: 200 }} src={WelcomeImage} alt="Welcome" />
          </Stack>
        </Grid>
      </Grid>
    </MainCard>
  );
}
