// angular/able-pro-angular-material-3.2.0/full-version/src/app/demo/pages/admin-panel/invoice/invoice-create/invoice-create.component.ts
// angular import
import { ChangeDetectorRef, Component, inject } from '@angular/core';

// project import
import { SharedModule } from 'src/app/demo/shared/shared.module';
import { AddressDialogComponent } from './address-dialog/address-dialog.component';

// angular material
import { MatDialog } from '@angular/material/dialog';
import { MatTableDataSource } from '@angular/material/table';

export interface PeriodicElement {
  no: number;
  name: string;
  description: string;
  qty: number;
  price: number;
  amount: number;
}

interface AddressType {
  name?: string;
  address?: string;
  mobile?: string;
  email?: string;
}

@Component({
  selector: 'app-invoice-create',
  imports: [SharedModule],
  templateUrl: './invoice-create.component.html',
  styleUrl: './invoice-create.component.scss'
})
export class InvoiceCreateComponent {
  private dialog = inject(MatDialog);
  private cdr = inject(ChangeDetectorRef);

  elements: PeriodicElement[] = [{ no: 1, name: '', description: '', qty: 0, price: 0, amount: 0 }];

  // public props
  displayedColumns: string[] = ['no', 'name', 'description', 'qty', 'price', 'amount', 'action'];
  dataSource = new MatTableDataSource<PeriodicElement>(this.elements);
  selectedAddress: AddressType | null = null;
  newAddress: AddressType | null = null;
  discountPercent = 0;
  taxPercent = 0;

  addressList() {
    const dialogRef = this.dialog.open(AddressDialogComponent, {
      width: '700px'
    });

    dialogRef.afterClosed().subscribe((result) => {
      if (result) {
        this.selectedAddress = result;
      }
    });
  }
  addNewAddress() {
    const dialogRef = this.dialog.open(AddressDialogComponent, {
      width: '700px'
    });

    dialogRef.afterClosed().subscribe((result) => {
      if (result) {
        this.newAddress = result;
      }
    });
  }
  onInputChange(index: number, field: 'qty' | 'price', value: number): void {
    const item = this.elements[index];
    if (!item) return;

    item[field] = value;
    item.amount = item.qty * item.price;

    this.dataSource.data = [...this.elements]; // Refresh table
  }

  get subTotal(): number {
    return this.elements.reduce((sum, item) => sum + item.amount, 0);
  }

  get discountAmount(): number {
    return (this.subTotal * this.discountPercent) / 100;
  }

  get taxAmount(): number {
    return ((this.subTotal - this.discountAmount) * this.taxPercent) / 100;
  }

  get grandTotal(): number {
    return this.subTotal - this.discountAmount + this.taxAmount;
  }

  deleteItem(no: number): void {
    this.elements = this.elements.filter((item) => item.no !== no);
    this.dataSource.data = [...this.elements];
  }

  addNewItem(): void {
    const newItem = {
      no: this.elements.length > 0 ? Math.max(...this.elements.map((e) => e.no)) + 1 : 1,
      name: '',
      description: '',
      qty: 0,
      price: 0,
      amount: 0
    };
    this.elements.push(newItem);
    this.dataSource.data = [...this.elements];
  }
}

<div class="row">
  <div class="col-sm-12">
    <app-card [showHeader]="false">
      <div class="row g-3">
        <div class="col-sm-6 col-xl-3">
          <mat-form-field appearance="outline" class="w-100">
            <mat-label>Invoice id</mat-label>
            <input matInput type="text" placeholder="#xxxx" />
          </mat-form-field>
        </div>
        <div class="col-sm-6 col-xl-3">
          <mat-form-field appearance="outline" class="w-100">
            <mat-label>Status</mat-label>
            <mat-select value="select">
              <mat-option value="select">Please Select</mat-option>
              <mat-option value="Paid">Paid</mat-option>
              <mat-option value="unpaid">Unpaid</mat-option>
              <mat-option value="partial-2">Partial Paid</mat-option>
            </mat-select>
          </mat-form-field>
        </div>
        <div class="col-sm-6 col-xl-3">
          <mat-form-field appearance="outline" class="w-100">
            <mat-label>Start Date</mat-label>
            <input matInput type="datetime-local" placeholder="mm/dd/yyyy" />
          </mat-form-field>
        </div>
        <div class="col-sm-6 col-xl-3">
          <mat-form-field appearance="outline" class="w-100">
            <mat-label>Due Date</mat-label>
            <input matInput type="datetime-local" placeholder="mm/dd/yyyy" />
          </mat-form-field>
        </div>
        <div class="col-xl-6">
          <div class="border border-4 p-15 h-100">
            <div class="flex align-item-center justify-content-between m-b-10">
              <div class="f-w-600">From:</div>
              <button mat-button class="bg-accent-100 text-accent-500" (click)="addressList()">
                <div class="flex align-item-center gap-2">
                  <svg class="wid-15 hei-15 f-16">
                    <use xlink:href="assets/fonts/custom-icon.svg#custom-edit2"></use>
                  </svg>
                  Change
                </div>
              </button>
            </div>
            @if (selectedAddress) {
              <div class="f-16 f-w-600">{{ selectedAddress.name }}</div>
              <p class="m-b-0">{{ selectedAddress.address }}</p>
              <p class="m-b-0">{{ selectedAddress.mobile }}</p>
              <p class="m-b-0">{{ selectedAddress.email }}</p>
            } @else {
              <div class="f-16 f-w-600">Garcia-Cameron and Sons</div>
              <p class="m-b-0">8534 Saunders Hill Apt. 583</p>
              <p class="m-b-0">(970) 982-3353</p>
              <p class="m-b-0">brandon07&#64;pierce.com</p>
            }
          </div>
        </div>
        <div class="col-xl-6">
          <div class="border border-4 p-15 h-100">
            <div class="flex align-item-center justify-content-between m-b-10">
              <div class="f-w-600">To:</div>
              <button mat-button class="bg-accent-100 text-accent-500" (click)="addNewAddress()">
                <div class="flex align-item-center gap-2">
                  <svg class="wid-15 hei-15 f-16">
                    <use xlink:href="assets/fonts/custom-icon.svg#custom-add-circle"></use>
                  </svg>
                  Add
                </div>
              </button>
            </div>
            @if (newAddress) {
              <div class="f-16 f-w-600">{{ newAddress.name }}</div>
              <p class="m-b-0">{{ newAddress.address }}</p>
              <p class="m-b-0">{{ newAddress.mobile }}</p>
              <p class="m-b-0">{{ newAddress.email }}</p>
            }
          </div>
        </div>
        <div class="col-12">
          <div class="f-16 f-w-600">Detail</div>
          <div class="table-responsive">
            <table mat-table [dataSource]="dataSource" class="mat-elevation-z8">
              <ng-container matColumnDef="no">
                <th mat-header-cell *matHeaderCellDef>#</th>
                <td mat-cell *matCellDef="let element" class="text-nowrap">{{ element.no }}</td>
              </ng-container>
              <ng-container matColumnDef="name">
                <th mat-header-cell *matHeaderCellDef>
                  <span class="text-warn-500">*</span>
                  NAME
                </th>
                <td mat-cell *matCellDef="let element" class="text-nowrap">
                  <div class="input-group">
                    <mat-form-field appearance="outline" class="w-100">
                      <input matInput type="text" [(ngModel)]="element.name" />
                    </mat-form-field>
                  </div>
                </td>
              </ng-container>
              <ng-container matColumnDef="description">
                <th mat-header-cell *matHeaderCellDef>
                  <span class="text-warn-500">*</span>
                  DESCRIPTION
                </th>
                <td mat-cell *matCellDef="let element" class="text-nowrap">
                  <div class="input-group">
                    <mat-form-field appearance="outline" class="w-100">
                      <input matInput type="text" [(ngModel)]="element.description" />
                    </mat-form-field>
                  </div>
                </td>
              </ng-container>
              <ng-container matColumnDef="qty">
                <th mat-header-cell *matHeaderCellDef>
                  <span class="text-warn-500">*</span>
                  QTY
                </th>
                <td mat-cell *matCellDef="let element" class="text-nowrap">
                  <div class="input-group">
                    <mat-form-field appearance="outline" class="w-100">
                      <input
                        matInput
                        type="number"
                        [(ngModel)]="element.qty"
                        (input)="onInputChange(dataSource.data.indexOf(element), 'qty', $event.target.valueAsNumber)"
                      />
                    </mat-form-field>
                  </div>
                </td>
              </ng-container>
              <ng-container matColumnDef="price">
                <th mat-header-cell *matHeaderCellDef>
                  <span class="text-warn-500">*</span>
                  PRICE
                </th>
                <td mat-cell *matCellDef="let element" class="text-nowrap">
                  <div class="input-group">
                    <mat-form-field appearance="outline" class="w-100">
                      <input
                        matInput
                        type="number"
                        [(ngModel)]="element.price"
                        (input)="onInputChange(dataSource.data.indexOf(element), 'price', $event.target.valueAsNumber)"
                      />
                    </mat-form-field>
                  </div>
                </td>
              </ng-container>
              <ng-container matColumnDef="amount">
                <th mat-header-cell *matHeaderCellDef>
                  <span class="text-warn-500">*</span>
                  TOTAL AMOUNT
                </th>
                <td mat-cell *matCellDef="let element" class="text-nowrap text-center">${{ element.amount.toFixed(2) }}</td>
              </ng-container>
              <ng-container matColumnDef="action">
                <th mat-header-cell *matHeaderCellDef>
                  <span class="text-warn-500">*</span>
                  ACTION
                </th>
                <td mat-cell *matCellDef="let element" class="text-nowrap">
                  <a href="javascript:" class="avatar avatar-s text-warn-500" (click)="deleteItem(element.no)">
                    <i class="ti ti-trash f-20"></i>
                  </a>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; let i = index; columns: displayedColumns"></tr>
            </table>
          </div>
          <div class="text-start">
            <mat-divider class="m-b-25 m-t-0"></mat-divider>
            <button mat-button class="bg-primary-50 text-primary-500" (click)="addNewItem()">
              <div class="flex align-item-center gap-2">
                <i class="ti ti-plus"></i>
                Add new item
              </div>
            </button>
          </div>
        </div>
        <div class="col-12">
          <div class="invoice-total">
            <div class="row">
              <div class="col-6">
                <div class="m-b-15">
                  <mat-form-field appearance="outline" class="w-100">
                    <mat-label>Discount(%)</mat-label>
                    <input matInput type="number" [(ngModel)]="discountPercent" />
                  </mat-form-field>
                </div>
              </div>
              <div class="col-6">
                <div class="m-b-15">
                  <mat-form-field appearance="outline" class="w-100">
                    <mat-label>Taxes(%)</mat-label>
                    <input matInput type="number" [(ngModel)]="taxPercent" />
                  </mat-form-field>
                </div>
              </div>
              <div class="col-6"><p class="text-muted m-b-5 text-start">Sub Total :</p></div>
              <div class="col-6">
                <p class="f-w-600 m-b-5 text-end">${{ subTotal.toFixed(2) }}</p>
              </div>
              <div class="col-6"><p class="text-muted mb-1 text-start">Discount :</p></div>
              <div class="col-6">
                <p class="f-w-600 m-b-5 text-end text-success">${{ discountAmount.toFixed(2) }}</p>
              </div>
              <div class="col-6"><p class="text-muted m-b-5 text-start">Taxes :</p></div>
              <div class="col-6">
                <p class="f-w-600 m-b-5 text-end">${{ taxAmount.toFixed(2) }}</p>
              </div>
              <div class="col-6"><p class="f-w-600 m-b-5 text-start">Grand Total :</p></div>
              <div class="col-6">
                <p class="f-w-600 m-b-5 text-end">${{ grandTotal.toFixed(2) }}</p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12">
          <div>
            <mat-form-field appearance="outline" class="w-100">
              <mat-label>Note</mat-label>
              <textarea matInput rows="3" placeholder="Note"></textarea>
            </mat-form-field>
          </div>
        </div>
        <div class="col-12">
          <div class="row align-item-end justify-content-between g-3">
            <div class="col-sm-auto">
              <div class="input-group">
                <mat-form-field appearance="outline" class="w-100">
                  <mat-label>Set Currency*</mat-label>
                  <mat-select value="usd">
                    <mat-option value="usd">USD (US Dollar)</mat-option>
                    <mat-option value="inr">INR (Rupes)</mat-option>
                  </mat-select>
                </mat-form-field>
              </div>
            </div>
            <div class="col-sm-auto">
              <button mat-stroked-button color="accent" class="m-r-10 m-b-10">Preview</button>
              <button mat-stroked-button color="accent" class="m-r-10 m-b-10">Save</button>
              <button mat-flat-button color="primary" class="m-b-10">Create & Send</button>
            </div>
          </div>
        </div>
      </div>
    </app-card>
  </div>
</div>

// svelte/able-pro-svelte-1.1.0/full-version/src/routes/(layout-vertical)/application/invoice-create/+page.svelte
<script>
  import Breadcrumb from '../../../../lib/Components/Layouts/Partials/Breadcrumb.svelte';
</script>

<svelte:head>
  <title>Create Invoice | Able Pro Dashboard Template</title>
</svelte:head>
<!-- [ Main Content ] start -->
<div class="pc-container">
  <div class="pc-content">
    <Breadcrumb item="Invoice" itemActive="Create" />
    <!-- [ Main Content ] start -->
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-body">
            <div class="row g-3">
              <div class="col-sm-6 col-xl-3">
                <div>
                  <label class="form-label">Invoice id</label>
                  <input type="text" class="form-control" placeholder="#xxxx" />
                </div>
              </div>
              <div class="col-sm-6 col-xl-3">
                <div>
                  <label class="form-label">Status</label>
                  <select class="form-select" id="exampleFormControlSelect1">
                    <option>Please Select</option>
                    <option>Paid</option>
                    <option>Unpaid</option>
                    <option>Partial Paid</option>
                  </select>
                </div>
              </div>
              <div class="col-sm-6 col-xl-3">
                <div>
                  <label class="form-label">Start Date</label>
                  <input type="datetime-local" class="form-control" />
                </div>
              </div>
              <div class="col-sm-6 col-xl-3">
                <div>
                  <label class="form-label">Due Date</label>
                  <input type="datetime-local" class="form-control" />
                </div>
              </div>
              <div class="col-xl-6">
                <div class="border rounded p-3 h-100">
                  <div class="d-flex align-items-center justify-content-between mb-2">
                    <h6 class="mb-0">From:</h6>
                    <button
                      class="btn btn-sm btn-light-secondary d-flex align-items-center gap-2"
                      data-bs-toggle="modal"
                      data-bs-target="#address-edit_add-modal"><i class="ph-duotone ph-pencil-simple-line"></i> Change</button
                    >
                  </div>
                  <h5>Garcia-Cameron and Sons</h5>
                  <p class="mb-0">8534 Saunders Hill Apt. 583</p>
                  <p class="mb-0">(970) 982-3353</p>
                  <p class="mb-0">brandon07@pierce.com</p>
                </div>
              </div>
              <div class="col-xl-6">
                <div class="border rounded p-3 h-100">
                  <div class="d-flex align-items-center justify-content-between">
                    <h6 class="mb-0">To:</h6>
                    <button
                      class="btn btn-sm btn-light-secondary d-flex align-items-center gap-2"
                      data-bs-toggle="modal"
                      data-bs-target="#address-edit_add-modal"><i class="ph-duotone ph-plus-circle"></i> Add</button
                    >
                  </div>
                </div>
              </div>
              <div class="col-12">
                <h5>Detail</h5>
                <div class="table-responsive">
                  <table class="table table-hover mb-0">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th><span class="text-danger">*</span>Name</th>
                        <th><span class="text-danger">*</span>Description</th>
                        <th><span class="text-danger">*</span>Qty</th>
                        <th><span class="text-danger">*</span>Price</th>
                        <th>Total Amount</th>
                        <th class="text-center">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>1</td>
                        <td><input type="text" class="form-control" placeholder="Name" /></td>
                        <td><input type="text" class="form-control" placeholder="Description" /></td>
                        <td><input type="number" class="form-control" placeholder="Qty" /></td>
                        <td><input type="number" class="form-control" placeholder="Price" /></td>
                        <td>₹1.00</td>
                        <td class="text-center">
                          <a href="#!" class="avtar avtar-s btn-link-danger btn-pc-default"><i class="ti ti-trash f-20"></i></a>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="text-start">
                  <hr class="mb-4 mt-0 border-secondary border-opacity-50" />
                  <button class="btn btn-light-primary d-flex align-items-center gap-2"><i class="ti ti-plus"></i> Add new item</button>
                </div>
              </div>
              <div class="col-12">
                <div class="invoice-total ms-auto">
                  <div class="row">
                    <div class="col-6">
                      <div class="mb-3">
                        <label class="form-label">Discount(%)</label>
                        <input type="text" class="form-control" value="0" />
                      </div>
                    </div>
                    <div class="col-6">
                      <div class="mb-3">
                        <label class="form-label">Taxes(%)</label>
                        <input type="text" class="form-control" value="0" />
                      </div>
                    </div>
                    <div class="col-6"><p class="text-muted mb-1 text-start">Sub Total :</p></div>
                    <div class="col-6"><p class="f-w-600 mb-1 text-end">$20.00</p></div>
                    <div class="col-6"><p class="text-muted mb-1 text-start">Discount :</p></div>
                    <div class="col-6">
                      <p class="f-w-600 mb-1 text-end text-success">$10.00</p>
                    </div>
                    <div class="col-6"><p class="text-muted mb-1 text-start">Taxes :</p></div>
                    <div class="col-6"><p class="f-w-600 mb-1 text-end">$5.000</p></div>
                    <div class="col-6"><p class="f-w-600 mb-1 text-start">Grand Total :</p></div>
                    <div class="col-6"><p class="f-w-600 mb-1 text-end">$25.00</p></div>
                  </div>
                </div>
              </div>
              <div class="col-12">
                <div>
                  <label class="form-label">Note</label>
                  <textarea class="form-control" rows="3" placeholder="Note"></textarea>
                </div>
              </div>
              <div class="col-12">
                <div class="row align-items-end justify-content-between g-3">
                  <div class="col-sm-auto">
                    <label class="form-label">Set Currency*</label>
                    <select class="form-select w-auto">
                      <option>USD (US Dollar)</option>
                      <option>INR (Rupes)</option>
                    </select>
                  </div>
                  <div class="col-sm-auto btn-page">
                    <a href="/application/invoice-view" class="btn btn-outline-secondary">Preview</a>
                    <button class="btn btn-outline-secondary">Save</button>
                    <button class="btn btn-primary">Create & Send</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- [ Main Content ] end -->
  </div>
</div>
<div class="modal fade" id="address-edit_add-modal" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header justify-content-between">
        <div class="collapse multi-collapse show">
          <h5 class="mb-0">Select address</h5>
        </div>
        <div class="collapse multi-collapse">
          <h5 class="mb-0">Add New address</h5>
        </div>
        <div class="d-flex align-items-center justify-content-end">
          <div class="collapse multi-collapse show" data-bs-toggle="tooltip" title="Add New">
            <a href="#!" class="avtar avtar-s btn-link-secondary" data-bs-toggle="collapse" data-bs-target=".multi-collapse">
              <i class="ti ti-plus f-20"></i>
            </a>
          </div>
          <a href="#!" class="avtar avtar-s btn-link-danger" data-bs-dismiss="modal" data-bs-toggle="tooltip" title="Close">
            <i class="ti ti-x f-20"></i>
          </a>
        </div>
      </div>
      <div class="modal-body">
        <div class="collapse multi-collapse show">
          <div class="address-check-block">
            <div class="address-check border rounded p-3">
              <div class="form-check">
                <input type="radio" name="radio1" class="form-check-input input-primary" id="address-check-1" checked="" />
                <label class="form-check-label d-block" for="address-check-1">
                  <span class="h6 mb-0 d-block">Ian Carpenter <small class="text-muted">(Home)</small></span>
                  <span class="text-muted address-details">1754 Ureate Path, 695 Newga View, Seporcus, Rhode Island, Belgium - SA5 5BO</span
                  >
                  <span class="row align-items-center justify-content-between">
                    <span class="col-sm-6">
                      <span class="text-muted mb-0">+91 1234567890</span>
                    </span>
                    <span class="col-sm-6 text-sm-end">
                      <span class="address-btns d-flex align-items-center justify-content-end">
                        <a href="#!" class="avtar avtar-s btn-link-danger btn-pc-default me-1">
                          <i class="ti ti-trash f-20"></i>
                        </a>
                        <span class="btn btn-sm btn-outline-primary">Deliver to this address</span>
                      </span>
                    </span>
                  </span>
                </label>
              </div>
            </div>
            <div class="address-check border rounded p-3">
              <div class="form-check">
                <input type="radio" name="radio1" class="form-check-input input-primary" id="address-check-2" />
                <label class="form-check-label d-block" for="address-check-2">
                  <span class="h6 mb-0 d-block">Ian Carpenter <small class="text-muted">(Home)</small></span>
                  <span class="text-muted address-details">1754 Ureate Path, 695 Newga View, Seporcus, Rhode Island, Belgium - SA5 5BO</span
                  >
                  <span class="row align-items-center justify-content-between">
                    <span class="col-sm-6">
                      <span class="text-muted mb-0">+91 1234567890</span>
                    </span>
                    <span class="col-sm-6 text-sm-end">
                      <span class="address-btns d-flex align-items-center justify-content-end">
                        <a href="#!" class="avtar avtar-s btn-link-danger btn-pc-default me-1">
                          <i class="ti ti-trash f-20"></i>
                        </a>
                        <span class="btn btn-sm btn-outline-primary">Deliver to this address</span>
                      </span>
                    </span>
                  </span>
                </label>
              </div>
            </div>
            <div class="address-check border rounded p-3">
              <div class="form-check">
                <input type="radio" name="radio1" class="form-check-input input-primary" id="address-check-3" />
                <label class="form-check-label d-block" for="address-check-3">
                  <span class="h6 mb-0 d-block">Ian Carpenter <small class="text-muted">(Home)</small></span>
                  <span class="text-muted address-details">1754 Ureate Path, 695 Newga View, Seporcus, Rhode Island, Belgium - SA5 5BO</span
                  >
                  <span class="row align-items-center justify-content-between">
                    <span class="col-sm-6">
                      <span class="text-muted mb-0">+91 1234567890</span>
                    </span>
                    <span class="col-sm-6 text-sm-end">
                      <span class="address-btns d-flex align-items-center justify-content-end">
                        <a href="#!" class="avtar avtar-s btn-link-danger btn-pc-default me-1">
                          <i class="ti ti-trash f-20"></i>
                        </a>
                        <span class="btn btn-sm btn-outline-primary">Deliver to this address</span>
                      </span>
                    </span>
                  </span>
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="collapse multi-collapse">
          <div class="row">
            <div class="col-12">
              <div class="mb-3 row align-items-center">
                <label class="col-lg-4 col-form-label">Address Type :<small class="text-muted d-block">Enter Add Type</small></label>
                <div class="col-lg-8">
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="addtypecheck1" checked />
                    <label class="form-check-label" for="addtypecheck1"> Home (All day Delivery) </label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="addtypecheck2" />
                    <label class="form-check-label" for="addtypecheck2"> Work (Between 10 AM to 5 PM) </label>
                  </div>
                </div>
              </div>
              <div class="mb-3 row">
                <label class="col-lg-4 col-form-label">First Name :<small class="text-muted d-block">Enter your first name</small></label>
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="mb-3 row">
                <label class="col-lg-4 col-form-label">Last Name :<small class="text-muted d-block">Enter your last name</small></label>
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="mb-3 row">
                <label class="col-lg-4 col-form-label">Email Id :<small class="text-muted d-block">Enter Email id</small></label>
                <div class="col-lg-8">
                  <input type="email" class="form-control" />
                </div>
              </div>
              <div class="mb-3 row">
                <label class="col-lg-4 col-form-label"
                  >Date of Birth :<small class="text-muted d-block">Enter the date of birth</small></label
                >
                <div class="col-lg-8">
                  <input type="date" class="form-control" />
                </div>
              </div>
              <div class="mb-3 row">
                <label class="col-lg-4 col-form-label">Phone number :<small class="text-muted d-block">Enter Phone number</small></label>
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="mb-3 row">
                <label class="col-lg-4 col-form-label">City :<small class="text-muted d-block">Enter City name</small></label>
                <div class="col-lg-8">
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="mb-3">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="checkaddres" checked />
                  <label class="form-check-label" for="checkaddres"> Save this new address for future shipping </label>
                </div>
              </div>
              <div class="text-end btn-page mb-0 mt-4">
                <button class="btn btn-outline-secondary" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse"
                  >Cancel</button
                >
                <button class="btn btn-primary" data-bs-dismiss="modal">Save & Deliver to this Address</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer justify-content-between collapse multi-collapse show">
        <ul class="list-inline me-auto mb-0">
          <li class="list-inline-item align-bottom">
            <a href="#!" class="avtar avtar-s btn-link-danger w-sm-auto" data-bs-toggle="tooltip" title="Delete">
              <i class="ti ti-trash f-18"></i>
            </a>
          </li>
        </ul>
        <div class="flex-grow-1 text-end">
          <button type="button" class="btn btn-link-danger" data-bs-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Save</button>
        </div>
      </div>
    </div>
  </div>
</div>
